config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :grades
  resources :students
  resources :teachers
  resources :groups

  root to: 'home#index'
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :grades
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :grades
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :trackable

  enum role: { admin: 0, teacher: 1, student: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def index
    if current_user.teacher?
      @grades = Grade.where(teacher_id: current_user.teacher.id)
    elsif current_user.student?
      @grades = Grade.where(student_id: current_user.student.id)
    else
      @grades = Grade.all
    end
  end

  def edit
    @grade = Grade.find(params[:id])
    authorize! :update, @grade
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @students = @group.students
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
    @grades = @student.grades
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def show
    @teacher = Teacher.find(params[:id])
    @grades = @teacher.grades
  end
end

app/views/grades/edit.html.erb
<h1>Edit Grade</h1>
<%= form_with(model: @grade, local: true) do |form| %>
  <div>
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>
  <div>
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/grades/index.html.erb
<h1>Your Grades</h1>
<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Score</th>
      <th>Teacher</th>
    </tr>
  </thead>
  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= grade.subject.name %></td>
        <td><%= grade.score %></td>
        <td><%= grade.teacher.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/grades/show.html.erb
<h1>Grade Details</h1>
<p><strong>Student:</strong> <%= @grade.student.name %></p>
<p><strong>Score:</strong> <%= @grade.score %></p>
<p><strong>Teacher:</strong> <%= @grade.teacher.name %></p>

app/views/groups/index.html.erb
<h1>Groups</h1>
<ul>
  <% @groups.each do |group| %>
    <li><%= link_to group.name, group_path(group) %></li>
  <% end %>
</ul>

app/views/groups/show.html.erb
<h1>Group: <%= @group.name %></h1>
<h2>Students:</h2>
<ul>
  <% @students.each do |student| %>
    <li><%= link_to student.name, student_path(student) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Student Performance Tracker</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/students/index.html.erb
<h1>Students</h1>
<ul>
  <% @students.each do |student| %>
    <li><%= link_to student.name, student_path(student) %></li>
  <% end %>
</ul>

app/views/students/show.html.erb
<h1>Student: <%= @student.name %></h1>
<h2>Grades:</h2>
<ul>
  <% @grades.each do |grade| %>
    <li><strong>Score:</strong> <%= grade.score %> | <strong>Teacher:</strong> <%= grade.teacher.name %></li>
  <% end %>
</ul>

app/views/teachers/index.html.erb
<h1>Teachers</h1>
<ul>
  <% @teachers.each do |teacher| %>
    <li><%= link_to teacher.name, teacher_path(teacher) %></li>
  <% end %>
</ul>

app/views/teachers/show.html.erb
<h1>Teacher: <%= @teacher.name %></h1>
<h2>Grades Given:</h2>
<ul>
  <% @grades.each do |grade| %>
    <li><strong>Student:</strong> <%= grade.student.name %> | <strong>Score:</strong> <%= grade.score %></li>
  <% end %>
</ul>